# Generated by Django 5.1.3 on 2025-01-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simplecv", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cv",
            options={
                "get_latest_by": "-date_updated",
                "ordering": ["-date_updated"],
                "verbose_name": "CV",
                "verbose_name_plural": "CV's",
            },
        ),
        migrations.AddField(
            model_name="cv",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="cv",
            name="full_name",
            field=models.CharField(default=" ", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cv",
            name="image",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="cv",
            name="phone",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="cv",
            name="summary",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="cv",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("institution", models.CharField(max_length=50)),
                ("location", models.CharField(blank=True, max_length=50)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("result", models.CharField(blank=True, max_length=25)),
                ("focus", models.CharField(max_length=25)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="simplecv.cv",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=12)),
                ("url", models.URLField()),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="simplecv.cv",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("previous", models.CharField(blank=True, max_length=50)),
                ("staffed_by", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to="simplecv.cv",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=75)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("achievements", models.TextField(blank=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="simplecv.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("values", models.CharField(max_length=150)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="simplecv.cv",
                    ),
                ),
            ],
        ),
    ]
